// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ihozrsfnfmwmrkbzpqlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlob3pyc2ZuZm13bXJrYnpwcWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDM0NDcsImV4cCI6MjA3ODUxOTQ0N30.k60F5T-nkbTDXdlWa85ogk_xTtAB35b9ZIsIvCnDgOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);